<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = array(
            array('state_id' => '1','name' => 'اسکو'),
            array('state_id' => '1','name' => 'اهر'),
            array('state_id' => '1','name' => 'ایلخچی'),
            array('state_id' => '1','name' => 'آبش احمد'),
            array('state_id' => '1','name' => 'آذرشهر'),
            array('state_id' => '1','name' => 'آقکند'),
            array('state_id' => '1','name' => 'باسمنج'),
            array('state_id' => '1','name' => 'بخشایش'),
            array('state_id' => '1','name' => 'بستان آباد'),
            array('state_id' => '1','name' => 'بناب'),
            array('state_id' => '1','name' => 'بناب جدید'),
            array('state_id' => '1','name' => 'تبریز'),
            array('state_id' => '1','name' => 'ترک'),
            array('state_id' => '1','name' => 'ترکمانچای'),
            array('state_id' => '1','name' => 'تسوج'),
            array('state_id' => '1','name' => 'تیکمه داش'),
            array('state_id' => '1','name' => 'جلفا'),
            array('state_id' => '1','name' => 'خاروانا'),
            array('state_id' => '1','name' => 'خامنه'),
            array('state_id' => '1','name' => 'خراجو'),
            array('state_id' => '1','name' => 'خسروشهر'),
            array('state_id' => '1','name' => 'خضرلو'),
            array('state_id' => '1','name' => 'خمارلو'),
            array('state_id' => '1','name' => 'خواجه'),
            array('state_id' => '1','name' => 'دوزدوزان'),
            array('state_id' => '1','name' => 'زرنق'),
            array('state_id' => '1','name' => 'زنوز'),
            array('state_id' => '1','name' => 'سراب'),
            array('state_id' => '1','name' => 'سردرود'),
            array('state_id' => '1','name' => 'سهند'),
            array('state_id' => '1','name' => 'سیس'),
            array('state_id' => '1','name' => 'سیه رود'),
            array('state_id' => '1','name' => 'شبستر'),
            array('state_id' => '1','name' => 'شربیان'),
            array('state_id' => '1','name' => 'شرفخانه'),
            array('state_id' => '1','name' => 'شندآباد'),
            array('state_id' => '1','name' => 'صوفیان'),
            array('state_id' => '1','name' => 'عجب شیر'),
            array('state_id' => '1','name' => 'قره آغاج'),
            array('state_id' => '1','name' => 'کشکسرای'),
            array('state_id' => '1','name' => 'کلوانق'),
            array('state_id' => '1','name' => 'کلیبر'),
            array('state_id' => '1','name' => 'کوزه کنان'),
            array('state_id' => '1','name' => 'گوگان'),
            array('state_id' => '1','name' => 'لیلان'),
            array('state_id' => '1','name' => 'مراغه'),
            array('state_id' => '1','name' => 'مرند'),
            array('state_id' => '1','name' => 'ملکان'),
            array('state_id' => '1','name' => 'ملک کیان'),
            array('state_id' => '1','name' => 'ممقان'),
            array('state_id' => '1','name' => 'مهربان'),
            array('state_id' => '1','name' => 'میانه'),
            array('state_id' => '1','name' => 'نظرکهریزی'),
            array('state_id' => '1','name' => 'هادی شهر'),
            array('state_id' => '1','name' => 'هرگلان'),
            array('state_id' => '1','name' => 'هریس'),
            array('state_id' => '1','name' => 'هشترود'),
            array('state_id' => '1','name' => 'هوراند'),
            array('state_id' => '1','name' => 'وایقان'),
            array('state_id' => '1','name' => 'ورزقان'),
            array('state_id' => '1','name' => 'یامچی'),
            array('state_id' => '2','name' => 'ارومیه'),
            array('state_id' => '2','name' => 'اشنویه'),
            array('state_id' => '2','name' => 'ایواوغلی'),
            array('state_id' => '2','name' => 'آواجیق'),
            array('state_id' => '2','name' => 'باروق'),
            array('state_id' => '2','name' => 'بازرگان'),
            array('state_id' => '2','name' => 'بوکان'),
            array('state_id' => '2','name' => 'پلدشت'),
            array('state_id' => '2','name' => 'پیرانشهر'),
            array('state_id' => '2','name' => 'تازه شهر'),
            array('state_id' => '2','name' => 'تکاب'),
            array('state_id' => '2','name' => 'چهاربرج'),
            array('state_id' => '2','name' => 'خوی'),
            array('state_id' => '2','name' => 'دیزج دیز'),
            array('state_id' => '2','name' => 'ربط'),
            array('state_id' => '2','name' => 'سردشت'),
            array('state_id' => '2','name' => 'سرو'),
            array('state_id' => '2','name' => 'سلماس'),
            array('state_id' => '2','name' => 'سیلوانه'),
            array('state_id' => '2','name' => 'سیمینه'),
            array('state_id' => '2','name' => 'سیه چشمه'),
            array('state_id' => '2','name' => 'شاهین دژ'),
            array('state_id' => '2','name' => 'شوط'),
            array('state_id' => '2','name' => 'فیرورق'),
            array('state_id' => '2','name' => 'قره ضیاءالدین'),
            array('state_id' => '2','name' => 'قطور'),
            array('state_id' => '2','name' => 'قوشچی'),
            array('state_id' => '2','name' => 'کشاورز'),
            array('state_id' => '2','name' => 'گردکشانه'),
            array('state_id' => '2','name' => 'ماکو'),
            array('state_id' => '2','name' => 'محمدیار'),
            array('state_id' => '2','name' => 'محمودآباد'),
            array('state_id' => '2','name' => 'مهاباد'),
            array('state_id' => '2','name' => 'میاندوآب'),
            array('state_id' => '2','name' => 'میرآباد'),
            array('state_id' => '2','name' => 'نالوس'),
            array('state_id' => '2','name' => 'نقده'),
            array('state_id' => '2','name' => 'نوشین'),
            array('state_id' => '3','name' => 'اردبیل'),
            array('state_id' => '3','name' => 'اصلاندوز'),
            array('state_id' => '3','name' => 'آبی بیگلو'),
            array('state_id' => '3','name' => 'بیله سوار'),
            array('state_id' => '3','name' => 'پارس آباد'),
            array('state_id' => '3','name' => 'تازه کند'),
            array('state_id' => '3','name' => 'تازه کندانگوت'),
            array('state_id' => '3','name' => 'جعفرآباد'),
            array('state_id' => '3','name' => 'خلخال'),
            array('state_id' => '3','name' => 'رضی'),
            array('state_id' => '3','name' => 'سرعین'),
            array('state_id' => '3','name' => 'عنبران'),
            array('state_id' => '3','name' => 'فخرآباد'),
            array('state_id' => '3','name' => 'کلور'),
            array('state_id' => '3','name' => 'کوراییم'),
            array('state_id' => '3','name' => 'گرمی'),
            array('state_id' => '3','name' => 'گیوی'),
            array('state_id' => '3','name' => 'لاهرود'),
            array('state_id' => '3','name' => 'مشگین شهر'),
            array('state_id' => '3','name' => 'نمین'),
            array('state_id' => '3','name' => 'نیر'),
            array('state_id' => '3','name' => 'هشتجین'),
            array('state_id' => '3','name' => 'هیر'),
            array('state_id' => '4','name' => 'ابریشم'),
            array('state_id' => '4','name' => 'ابوزیدآباد'),
            array('state_id' => '4','name' => 'اردستان'),
            array('state_id' => '4','name' => 'اژیه'),
            array('state_id' => '4','name' => 'اصفهان'),
            array('state_id' => '4','name' => 'افوس'),
            array('state_id' => '4','name' => 'انارک'),
            array('state_id' => '4','name' => 'ایمانشهر'),
            array('state_id' => '4','name' => 'آران وبیدگل'),
            array('state_id' => '4','name' => 'بادرود'),
            array('state_id' => '4','name' => 'باغ بهادران'),
            array('state_id' => '4','name' => 'بافران'),
            array('state_id' => '4','name' => 'برزک'),
            array('state_id' => '4','name' => 'برف انبار'),
            array('state_id' => '4','name' => 'بهاران شهر'),
            array('state_id' => '4','name' => 'بهارستان'),
            array('state_id' => '4','name' => 'بوئین و میاندشت'),
            array('state_id' => '4','name' => 'پیربکران'),
            array('state_id' => '4','name' => 'تودشک'),
            array('state_id' => '4','name' => 'تیران'),
            array('state_id' => '4','name' => 'جندق'),
            array('state_id' => '4','name' => 'جوزدان'),
            array('state_id' => '4','name' => 'جوشقان و کامو'),
            array('state_id' => '4','name' => 'چادگان'),
            array('state_id' => '4','name' => 'چرمهین'),
            array('state_id' => '4','name' => 'چمگردان'),
            array('state_id' => '4','name' => 'حبیب آباد'),
            array('state_id' => '4','name' => 'حسن آباد'),
            array('state_id' => '4','name' => 'حنا'),
            array('state_id' => '4','name' => 'خالدآباد'),
            array('state_id' => '4','name' => 'خمینی شهر'),
            array('state_id' => '4','name' => 'خوانسار'),
            array('state_id' => '4','name' => 'خور'),
            array('state_id' => '4','name' => 'خورزوق'),
            array('state_id' => '4','name' => 'داران'),
            array('state_id' => '4','name' => 'دامنه'),
            array('state_id' => '4','name' => 'درچه'),
            array('state_id' => '4','name' => 'دستگرد'),
            array('state_id' => '4','name' => 'دهاقان'),
            array('state_id' => '4','name' => 'دهق'),
            array('state_id' => '4','name' => 'دولت آباد'),
            array('state_id' => '4','name' => 'دیزیچه'),
            array('state_id' => '4','name' => 'رزوه'),
            array('state_id' => '4','name' => 'رضوانشهر'),
            array('state_id' => '4','name' => 'زاینده رود'),
            array('state_id' => '4','name' => 'زرین شهر'),
            array('state_id' => '4','name' => 'زواره'),
            array('state_id' => '4','name' => 'زیباشهر'),
            array('state_id' => '4','name' => 'سده لنجان'),
            array('state_id' => '4','name' => 'سفیدشهر'),
            array('state_id' => '4','name' => 'سگزی'),
            array('state_id' => '4','name' => 'سمیرم'),
            array('state_id' => '4','name' => 'شاهین شهر'),
            array('state_id' => '4','name' => 'شهرضا'),
            array('state_id' => '4','name' => 'طالخونچه'),
            array('state_id' => '4','name' => 'عسگران'),
            array('state_id' => '4','name' => 'علویجه'),
            array('state_id' => '4','name' => 'فرخی'),
            array('state_id' => '4','name' => 'فریدونشهر'),
            array('state_id' => '4','name' => 'فلاورجان'),
            array('state_id' => '4','name' => 'فولادشهر'),
            array('state_id' => '4','name' => 'قمصر'),
            array('state_id' => '4','name' => 'قهجاورستان'),
            array('state_id' => '4','name' => 'قهدریجان'),
            array('state_id' => '4','name' => 'کاشان'),
            array('state_id' => '4','name' => 'کرکوند'),
            array('state_id' => '4','name' => 'کلیشاد و سودرجان'),
            array('state_id' => '4','name' => 'کمشچه'),
            array('state_id' => '4','name' => 'کمه'),
            array('state_id' => '4','name' => 'کهریزسنگ'),
            array('state_id' => '4','name' => 'کوشک'),
            array('state_id' => '4','name' => 'کوهپایه'),
            array('state_id' => '4','name' => 'گرگاب'),
            array('state_id' => '4','name' => 'گزبرخوار'),
            array('state_id' => '4','name' => 'گلپایگان'),
            array('state_id' => '4','name' => 'گلدشت'),
            array('state_id' => '4','name' => 'گلشهر'),
            array('state_id' => '4','name' => 'گوگد'),
            array('state_id' => '4','name' => 'لای بید'),
            array('state_id' => '4','name' => 'مبارکه'),
            array('state_id' => '4','name' => 'مجلسی'),
            array('state_id' => '4','name' => 'محمدآباد'),
            array('state_id' => '4','name' => 'مشکات'),
            array('state_id' => '4','name' => 'منظریه'),
            array('state_id' => '4','name' => 'مهاباد'),
            array('state_id' => '4','name' => 'میمه'),
            array('state_id' => '4','name' => 'نائین'),
            array('state_id' => '4','name' => 'نجف آباد'),
            array('state_id' => '4','name' => 'نصرآباد'),
            array('state_id' => '4','name' => 'نطنز'),
            array('state_id' => '4','name' => 'نوش آباد'),
            array('state_id' => '4','name' => 'نیاسر'),
            array('state_id' => '4','name' => 'نیک آباد'),
            array('state_id' => '4','name' => 'هرند'),
            array('state_id' => '4','name' => 'ورزنه'),
            array('state_id' => '4','name' => 'ورنامخواست'),
            array('state_id' => '4','name' => 'وزوان'),
            array('state_id' => '4','name' => 'ونک'),
            array('state_id' => '5','name' => 'اسارا'),
            array('state_id' => '5','name' => 'اشتهارد'),
            array('state_id' => '5','name' => 'تنکمان'),
            array('state_id' => '5','name' => 'چهارباغ'),
            array('state_id' => '5','name' => 'سیف آباد'),
            array('state_id' => '5','name' => 'شهر جدید هشتگرد'),
            array('state_id' => '5','name' => 'طالقان'),
            array('state_id' => '5','name' => 'کرج'),
            array('state_id' => '5','name' => 'کمال شهر'),
            array('state_id' => '5','name' => 'کوهسار'),
            array('state_id' => '5','name' => 'گرمدره'),
            array('state_id' => '5','name' => 'ماهدشت'),
            array('state_id' => '5','name' => 'محمدشهر'),
            array('state_id' => '5','name' => 'مشکین دشت'),
            array('state_id' => '5','name' => 'نظرآباد'),
            array('state_id' => '5','name' => 'هشتگرد'),
            array('state_id' => '6','name' => 'ارکواز'),
            array('state_id' => '6','name' => 'ایلام'),
            array('state_id' => '6','name' => 'ایوان'),
            array('state_id' => '6','name' => 'آبدانان'),
            array('state_id' => '6','name' => 'آسمان آباد'),
            array('state_id' => '6','name' => 'بدره'),
            array('state_id' => '6','name' => 'پهله'),
            array('state_id' => '6','name' => 'توحید'),
            array('state_id' => '6','name' => 'چوار'),
            array('state_id' => '6','name' => 'دره شهر'),
            array('state_id' => '6','name' => 'دلگشا'),
            array('state_id' => '6','name' => 'دهلران'),
            array('state_id' => '6','name' => 'زرنه'),
            array('state_id' => '6','name' => 'سراب باغ'),
            array('state_id' => '6','name' => 'سرابله'),
            array('state_id' => '6','name' => 'صالح آباد'),
            array('state_id' => '6','name' => 'لومار'),
            array('state_id' => '6','name' => 'مهران'),
            array('state_id' => '6','name' => 'مورموری'),
            array('state_id' => '6','name' => 'موسیان'),
            array('state_id' => '6','name' => 'میمه'),
            array('state_id' => '7','name' => 'امام حسن'),
            array('state_id' => '7','name' => 'انارستان'),
            array('state_id' => '7','name' => 'اهرم'),
            array('state_id' => '7','name' => 'آب پخش'),
            array('state_id' => '7','name' => 'آبدان'),
            array('state_id' => '7','name' => 'برازجان'),
            array('state_id' => '7','name' => 'بردخون'),
            array('state_id' => '7','name' => 'بندردیر'),
            array('state_id' => '7','name' => 'بندردیلم'),
            array('state_id' => '7','name' => 'بندرریگ'),
            array('state_id' => '7','name' => 'بندرکنگان'),
            array('state_id' => '7','name' => 'بندرگناوه'),
            array('state_id' => '7','name' => 'بنک'),
            array('state_id' => '7','name' => 'بوشهر'),
            array('state_id' => '7','name' => 'تنگ ارم'),
            array('state_id' => '7','name' => 'جم'),
            array('state_id' => '7','name' => 'چغادک'),
            array('state_id' => '7','name' => 'خارک'),
            array('state_id' => '7','name' => 'خورموج'),
            array('state_id' => '7','name' => 'دالکی'),
            array('state_id' => '7','name' => 'دلوار'),
            array('state_id' => '7','name' => 'ریز'),
            array('state_id' => '7','name' => 'سعدآباد'),
            array('state_id' => '7','name' => 'سیراف'),
            array('state_id' => '7','name' => 'شبانکاره'),
            array('state_id' => '7','name' => 'شنبه'),
            array('state_id' => '7','name' => 'عسلویه'),
            array('state_id' => '7','name' => 'کاکی'),
            array('state_id' => '7','name' => 'کلمه'),
            array('state_id' => '7','name' => 'نخل تقی'),
            array('state_id' => '7','name' => 'وحدتیه'),
            array('state_id' => '8','name' => 'ارجمند'),
            array('state_id' => '8','name' => 'اسلامشهر'),
            array('state_id' => '8','name' => 'اندیشه'),
            array('state_id' => '8','name' => 'آبسرد'),
            array('state_id' => '8','name' => 'آبعلی'),
            array('state_id' => '8','name' => 'باغستان'),
            array('state_id' => '8','name' => 'باقرشهر'),
            array('state_id' => '8','name' => 'بومهن'),
            array('state_id' => '8','name' => 'پاکدشت'),
            array('state_id' => '8','name' => 'پردیس'),
            array('state_id' => '8','name' => 'پیشوا'),
            array('state_id' => '8','name' => 'تهران'),
            array('state_id' => '8','name' => 'جوادآباد'),
            array('state_id' => '8','name' => 'چهاردانگه'),
            array('state_id' => '8','name' => 'حسن آباد'),
            array('state_id' => '8','name' => 'دماوند'),
            array('state_id' => '8','name' => 'دیزین'),
            array('state_id' => '8','name' => 'ری'),
            array('state_id' => '8','name' => 'رباط کریم'),
            array('state_id' => '8','name' => 'رودهن'),
            array('state_id' => '8','name' => 'شاهدشهر'),
            array('state_id' => '8','name' => 'شریف آباد'),
            array('state_id' => '8','name' => 'شمشک'),
            array('state_id' => '8','name' => 'شهریار'),
            array('state_id' => '8','name' => 'صالح آباد'),
            array('state_id' => '8','name' => 'صباشهر'),
            array('state_id' => '8','name' => 'صفادشت'),
            array('state_id' => '8','name' => 'فردوسیه'),
            array('state_id' => '8','name' => 'فشم'),
            array('state_id' => '8','name' => 'فیروزکوه'),
            array('state_id' => '8','name' => 'قدس'),
            array('state_id' => '8','name' => 'قرچک'),
            array('state_id' => '8','name' => 'کهریزک'),
            array('state_id' => '8','name' => 'کیلان'),
            array('state_id' => '8','name' => 'گلستان'),
            array('state_id' => '8','name' => 'لواسان'),
            array('state_id' => '8','name' => 'ملارد'),
            array('state_id' => '8','name' => 'میگون'),
            array('state_id' => '8','name' => 'نسیم شهر'),
            array('state_id' => '8','name' => 'نصیرآباد'),
            array('state_id' => '8','name' => 'وحیدیه'),
            array('state_id' => '8','name' => 'ورامین'),
            array('state_id' => '9','name' => 'اردل'),
            array('state_id' => '9','name' => 'آلونی'),
            array('state_id' => '9','name' => 'باباحیدر'),
            array('state_id' => '9','name' => 'بروجن'),
            array('state_id' => '9','name' => 'بلداجی'),
            array('state_id' => '9','name' => 'بن'),
            array('state_id' => '9','name' => 'جونقان'),
            array('state_id' => '9','name' => 'چلگرد'),
            array('state_id' => '9','name' => 'سامان'),
            array('state_id' => '9','name' => 'سفیددشت'),
            array('state_id' => '9','name' => 'سودجان'),
            array('state_id' => '9','name' => 'سورشجان'),
            array('state_id' => '9','name' => 'شلمزار'),
            array('state_id' => '9','name' => 'شهرکرد'),
            array('state_id' => '9','name' => 'طاقانک'),
            array('state_id' => '9','name' => 'فارسان'),
            array('state_id' => '9','name' => 'فرادبنه'),
            array('state_id' => '9','name' => 'فرخ شهر'),
            array('state_id' => '9','name' => 'کیان'),
            array('state_id' => '9','name' => 'گندمان'),
            array('state_id' => '9','name' => 'گهرو'),
            array('state_id' => '9','name' => 'لردگان'),
            array('state_id' => '9','name' => 'مال خلیفه'),
            array('state_id' => '9','name' => 'ناغان'),
            array('state_id' => '9','name' => 'نافچ'),
            array('state_id' => '9','name' => 'نقنه'),
            array('state_id' => '9','name' => 'هفشجان'),
            array('state_id' => '10','name' => 'ارسک'),
            array('state_id' => '10','name' => 'اسدیه'),
            array('state_id' => '10','name' => 'اسفدن'),
            array('state_id' => '10','name' => 'اسلامیه'),
            array('state_id' => '10','name' => 'آرین شهر'),
            array('state_id' => '10','name' => 'آیسک'),
            array('state_id' => '10','name' => 'بشرویه'),
            array('state_id' => '10','name' => 'بیرجند'),
            array('state_id' => '10','name' => 'حاجی آباد'),
            array('state_id' => '10','name' => 'خضری دشت بیاض'),
            array('state_id' => '10','name' => 'خوسف'),
            array('state_id' => '10','name' => 'زهان'),
            array('state_id' => '10','name' => 'سرایان'),
            array('state_id' => '10','name' => 'سربیشه'),
            array('state_id' => '10','name' => 'سه قلعه'),
            array('state_id' => '10','name' => 'شوسف'),
            array('state_id' => '10','name' => 'طبس '),
            array('state_id' => '10','name' => 'فردوس'),
            array('state_id' => '10','name' => 'قاین'),
            array('state_id' => '10','name' => 'قهستان'),
            array('state_id' => '10','name' => 'محمدشهر'),
            array('state_id' => '10','name' => 'مود'),
            array('state_id' => '10','name' => 'نهبندان'),
            array('state_id' => '10','name' => 'نیمبلوک'),
            array('state_id' => '11','name' => 'احمدآباد صولت'),
            array('state_id' => '11','name' => 'انابد'),
            array('state_id' => '11','name' => 'باجگیران'),
            array('state_id' => '11','name' => 'باخرز'),
            array('state_id' => '11','name' => 'بار'),
            array('state_id' => '11','name' => 'بایگ'),
            array('state_id' => '11','name' => 'بجستان'),
            array('state_id' => '11','name' => 'بردسکن'),
            array('state_id' => '11','name' => 'بیدخت'),
            array('state_id' => '11','name' => 'تایباد'),
            array('state_id' => '11','name' => 'تربت جام'),
            array('state_id' => '11','name' => 'تربت حیدریه'),
            array('state_id' => '11','name' => 'جغتای'),
            array('state_id' => '11','name' => 'جنگل'),
            array('state_id' => '11','name' => 'چاپشلو'),
            array('state_id' => '11','name' => 'چکنه'),
            array('state_id' => '11','name' => 'چناران'),
            array('state_id' => '11','name' => 'خرو'),
            array('state_id' => '11','name' => 'خلیل آباد'),
            array('state_id' => '11','name' => 'خواف'),
            array('state_id' => '11','name' => 'داورزن'),
            array('state_id' => '11','name' => 'درگز'),
            array('state_id' => '11','name' => 'در رود'),
            array('state_id' => '11','name' => 'دولت آباد'),
            array('state_id' => '11','name' => 'رباط سنگ'),
            array('state_id' => '11','name' => 'رشتخوار'),
            array('state_id' => '11','name' => 'رضویه'),
            array('state_id' => '11','name' => 'روداب'),
            array('state_id' => '11','name' => 'ریوش'),
            array('state_id' => '11','name' => 'سبزوار'),
            array('state_id' => '11','name' => 'سرخس'),
            array('state_id' => '11','name' => 'سفیدسنگ'),
            array('state_id' => '11','name' => 'سلامی'),
            array('state_id' => '11','name' => 'سلطان آباد'),
            array('state_id' => '11','name' => 'سنگان'),
            array('state_id' => '11','name' => 'شادمهر'),
            array('state_id' => '11','name' => 'شاندیز'),
            array('state_id' => '11','name' => 'ششتمد'),
            array('state_id' => '11','name' => 'شهرآباد'),
            array('state_id' => '11','name' => 'شهرزو'),
            array('state_id' => '11','name' => 'صالح آباد'),
            array('state_id' => '11','name' => 'طرقبه'),
            array('state_id' => '11','name' => 'عشق آباد'),
            array('state_id' => '11','name' => 'فرهادگرد'),
            array('state_id' => '11','name' => 'فریمان'),
            array('state_id' => '11','name' => 'فیروزه'),
            array('state_id' => '11','name' => 'فیض آباد'),
            array('state_id' => '11','name' => 'قاسم آباد'),
            array('state_id' => '11','name' => 'قدمگاه'),
            array('state_id' => '11','name' => 'قلندرآباد'),
            array('state_id' => '11','name' => 'قوچان'),
            array('state_id' => '11','name' => 'کاخک'),
            array('state_id' => '11','name' => 'کاریز'),
            array('state_id' => '11','name' => 'کاشمر'),
            array('state_id' => '11','name' => 'کدکن'),
            array('state_id' => '11','name' => 'کلات'),
            array('state_id' => '11','name' => 'کندر'),
            array('state_id' => '11','name' => 'گلمکان'),
            array('state_id' => '11','name' => 'گناباد'),
            array('state_id' => '11','name' => 'لطف آباد'),
            array('state_id' => '11','name' => 'مزدآوند'),
            array('state_id' => '11','name' => 'مشهد'),
            array('state_id' => '11','name' => 'ملک آباد'),
            array('state_id' => '11','name' => 'نشتیفان'),
            array('state_id' => '11','name' => 'نصرآباد'),
            array('state_id' => '11','name' => 'نقاب'),
            array('state_id' => '11','name' => 'نوخندان'),
            array('state_id' => '11','name' => 'نیشابور'),
            array('state_id' => '11','name' => 'نیل شهر'),
            array('state_id' => '11','name' => 'همت آباد'),
            array('state_id' => '11','name' => 'یونسی'),
            array('state_id' => '12','name' => 'اسفراین'),
            array('state_id' => '12','name' => 'ایور'),
            array('state_id' => '12','name' => 'آشخانه'),
            array('state_id' => '12','name' => 'بجنورد'),
            array('state_id' => '12','name' => 'پیش قلعه'),
            array('state_id' => '12','name' => 'تیتکانلو'),
            array('state_id' => '12','name' => 'جاجرم'),
            array('state_id' => '12','name' => 'حصارگرمخان'),
            array('state_id' => '12','name' => 'درق'),
            array('state_id' => '12','name' => 'راز'),
            array('state_id' => '12','name' => 'سنخواست'),
            array('state_id' => '12','name' => 'شوقان'),
            array('state_id' => '12','name' => 'شیروان'),
            array('state_id' => '12','name' => 'صفی آباد'),
            array('state_id' => '12','name' => 'فاروج'),
            array('state_id' => '12','name' => 'قاضی'),
            array('state_id' => '12','name' => 'گرمه'),
            array('state_id' => '12','name' => 'لوجلی'),
            array('state_id' => '13','name' => 'اروندکنار'),
            array('state_id' => '13','name' => 'الوان'),
            array('state_id' => '13','name' => 'امیدیه'),
            array('state_id' => '13','name' => 'اندیمشک'),
            array('state_id' => '13','name' => 'اهواز'),
            array('state_id' => '13','name' => 'ایذه'),
            array('state_id' => '13','name' => 'آبادان'),
            array('state_id' => '13','name' => 'آغاجاری'),
            array('state_id' => '13','name' => 'باغ ملک'),
            array('state_id' => '13','name' => 'بستان'),
            array('state_id' => '13','name' => 'بندرامام خمینی'),
            array('state_id' => '13','name' => 'بندرماهشهر'),
            array('state_id' => '13','name' => 'بهبهان'),
            array('state_id' => '13','name' => 'ترکالکی'),
            array('state_id' => '13','name' => 'جایزان'),
            array('state_id' => '13','name' => 'چمران'),
            array('state_id' => '13','name' => 'چویبده'),
            array('state_id' => '13','name' => 'حر'),
            array('state_id' => '13','name' => 'حسینیه'),
            array('state_id' => '13','name' => 'حمزه'),
            array('state_id' => '13','name' => 'حمیدیه'),
            array('state_id' => '13','name' => 'خرمشهر'),
            array('state_id' => '13','name' => 'دارخوین'),
            array('state_id' => '13','name' => 'دزآب'),
            array('state_id' => '13','name' => 'دزفول'),
            array('state_id' => '13','name' => 'دهدز'),
            array('state_id' => '13','name' => 'رامشیر'),
            array('state_id' => '13','name' => 'رامهرمز'),
            array('state_id' => '13','name' => 'رفیع'),
            array('state_id' => '13','name' => 'زهره'),
            array('state_id' => '13','name' => 'سالند'),
            array('state_id' => '13','name' => 'سردشت'),
            array('state_id' => '13','name' => 'سوسنگرد'),
            array('state_id' => '13','name' => 'شادگان'),
            array('state_id' => '13','name' => 'شاوور'),
            array('state_id' => '13','name' => 'شرافت'),
            array('state_id' => '13','name' => 'شوش'),
            array('state_id' => '13','name' => 'شوشتر'),
            array('state_id' => '13','name' => 'شیبان'),
            array('state_id' => '13','name' => 'صالح شهر'),
            array('state_id' => '13','name' => 'صفی آباد'),
            array('state_id' => '13','name' => 'صیدون'),
            array('state_id' => '13','name' => 'قلعه تل'),
            array('state_id' => '13','name' => 'قلعه خواجه'),
            array('state_id' => '13','name' => 'گتوند'),
            array('state_id' => '13','name' => 'لالی'),
            array('state_id' => '13','name' => 'مسجدسلیمان'),
            array('state_id' => '13','name' => 'ملاثانی'),
            array('state_id' => '13','name' => 'میانرود'),
            array('state_id' => '13','name' => 'مینوشهر'),
            array('state_id' => '13','name' => 'هفتگل'),
            array('state_id' => '13','name' => 'هندیجان'),
            array('state_id' => '13','name' => 'هویزه'),
            array('state_id' => '13','name' => 'ویس'),
            array('state_id' => '14','name' => 'ابهر'),
            array('state_id' => '14','name' => 'ارمغان خانه'),
            array('state_id' => '14','name' => 'آب بر'),
            array('state_id' => '14','name' => 'چورزق'),
            array('state_id' => '14','name' => 'حلب'),
            array('state_id' => '14','name' => 'خرمدره'),
            array('state_id' => '14','name' => 'دندی'),
            array('state_id' => '14','name' => 'زرین آباد'),
            array('state_id' => '14','name' => 'زرین رود'),
            array('state_id' => '14','name' => 'زنجان'),
            array('state_id' => '14','name' => 'سجاس'),
            array('state_id' => '14','name' => 'سلطانیه'),
            array('state_id' => '14','name' => 'سهرورد'),
            array('state_id' => '14','name' => 'صائین قلعه'),
            array('state_id' => '14','name' => 'قیدار'),
            array('state_id' => '14','name' => 'گرماب'),
            array('state_id' => '14','name' => 'ماه نشان'),
            array('state_id' => '14','name' => 'هیدج'),
            array('state_id' => '15','name' => 'امیریه'),
            array('state_id' => '15','name' => 'ایوانکی'),
            array('state_id' => '15','name' => 'آرادان'),
            array('state_id' => '15','name' => 'بسطام'),
            array('state_id' => '15','name' => 'بیارجمند'),
            array('state_id' => '15','name' => 'دامغان'),
            array('state_id' => '15','name' => 'درجزین'),
            array('state_id' => '15','name' => 'دیباج'),
            array('state_id' => '15','name' => 'سرخه'),
            array('state_id' => '15','name' => 'سمنان'),
            array('state_id' => '15','name' => 'شاهرود'),
            array('state_id' => '15','name' => 'شهمیرزاد'),
            array('state_id' => '15','name' => 'کلاته خیج'),
            array('state_id' => '15','name' => 'گرمسار'),
            array('state_id' => '15','name' => 'مجن'),
            array('state_id' => '15','name' => 'مهدی شهر'),
            array('state_id' => '15','name' => 'میامی'),
            array('state_id' => '16','name' => 'ادیمی'),
            array('state_id' => '16','name' => 'اسپکه'),
            array('state_id' => '16','name' => 'ایرانشهر'),
            array('state_id' => '16','name' => 'بزمان'),
            array('state_id' => '16','name' => 'بمپور'),
            array('state_id' => '16','name' => 'بنت'),
            array('state_id' => '16','name' => 'بنجار'),
            array('state_id' => '16','name' => 'پیشین'),
            array('state_id' => '16','name' => 'جالق'),
            array('state_id' => '16','name' => 'چابهار'),
            array('state_id' => '16','name' => 'خاش'),
            array('state_id' => '16','name' => 'دوست محمد'),
            array('state_id' => '16','name' => 'راسک'),
            array('state_id' => '16','name' => 'زابل'),
            array('state_id' => '16','name' => 'زابلی'),
            array('state_id' => '16','name' => 'زاهدان'),
            array('state_id' => '16','name' => 'زهک'),
            array('state_id' => '16','name' => 'سراوان'),
            array('state_id' => '16','name' => 'سرباز'),
            array('state_id' => '16','name' => 'سوران'),
            array('state_id' => '16','name' => 'سیرکان'),
            array('state_id' => '16','name' => 'علی اکبر'),
            array('state_id' => '16','name' => 'فنوج'),
            array('state_id' => '16','name' => 'قصرقند'),
            array('state_id' => '16','name' => 'کنارک'),
            array('state_id' => '16','name' => 'گشت'),
            array('state_id' => '16','name' => 'گلمورتی'),
            array('state_id' => '16','name' => 'محمدان'),
            array('state_id' => '16','name' => 'محمدآباد'),
            array('state_id' => '16','name' => 'محمدی'),
            array('state_id' => '16','name' => 'میرجاوه'),
            array('state_id' => '16','name' => 'نصرت آباد'),
            array('state_id' => '16','name' => 'نگور'),
            array('state_id' => '16','name' => 'نوک آباد'),
            array('state_id' => '16','name' => 'نیک شهر'),
            array('state_id' => '16','name' => 'هیدوچ'),
            array('state_id' => '17','name' => 'اردکان'),
            array('state_id' => '17','name' => 'ارسنجان'),
            array('state_id' => '17','name' => 'استهبان'),
            array('state_id' => '17','name' => 'اشکنان'),
            array('state_id' => '17','name' => 'افزر'),
            array('state_id' => '17','name' => 'اقلید'),
            array('state_id' => '17','name' => 'امام شهر'),
            array('state_id' => '17','name' => 'اهل'),
            array('state_id' => '17','name' => 'اوز'),
            array('state_id' => '17','name' => 'ایج'),
            array('state_id' => '17','name' => 'ایزدخواست'),
            array('state_id' => '17','name' => 'آباده'),
            array('state_id' => '17','name' => 'آباده طشک'),
            array('state_id' => '17','name' => 'باب انار'),
            array('state_id' => '17','name' => 'بالاده'),
            array('state_id' => '17','name' => 'بنارویه'),
            array('state_id' => '17','name' => 'بهمن'),
            array('state_id' => '17','name' => 'بوانات'),
            array('state_id' => '17','name' => 'بیرم'),
            array('state_id' => '17','name' => 'بیضا'),
            array('state_id' => '17','name' => 'جنت شهر'),
            array('state_id' => '17','name' => 'جهرم'),
            array('state_id' => '17','name' => 'جویم'),
            array('state_id' => '17','name' => 'زرین دشت'),
            array('state_id' => '17','name' => 'حسن آباد'),
            array('state_id' => '17','name' => 'خان زنیان'),
            array('state_id' => '17','name' => 'خاوران'),
            array('state_id' => '17','name' => 'خرامه'),
            array('state_id' => '17','name' => 'خشت'),
            array('state_id' => '17','name' => 'خنج'),
            array('state_id' => '17','name' => 'خور'),
            array('state_id' => '17','name' => 'داراب'),
            array('state_id' => '17','name' => 'داریان'),
            array('state_id' => '17','name' => 'دبیران'),
            array('state_id' => '17','name' => 'دژکرد'),
            array('state_id' => '17','name' => 'دهرم'),
            array('state_id' => '17','name' => 'دوبرجی'),
            array('state_id' => '17','name' => 'رامجرد'),
            array('state_id' => '17','name' => 'رونیز'),
            array('state_id' => '17','name' => 'زاهدشهر'),
            array('state_id' => '17','name' => 'زرقان'),
            array('state_id' => '17','name' => 'سده'),
            array('state_id' => '17','name' => 'سروستان'),
            array('state_id' => '17','name' => 'سعادت شهر'),
            array('state_id' => '17','name' => 'سورمق'),
            array('state_id' => '17','name' => 'سیدان'),
            array('state_id' => '17','name' => 'ششده'),
            array('state_id' => '17','name' => 'شهرپیر'),
            array('state_id' => '17','name' => 'شهرصدرا'),
            array('state_id' => '17','name' => 'شیراز'),
            array('state_id' => '17','name' => 'صغاد'),
            array('state_id' => '17','name' => 'صفاشهر'),
            array('state_id' => '17','name' => 'علامرودشت'),
            array('state_id' => '17','name' => 'فدامی'),
            array('state_id' => '17','name' => 'فراشبند'),
            array('state_id' => '17','name' => 'فسا'),
            array('state_id' => '17','name' => 'فیروزآباد'),
            array('state_id' => '17','name' => 'قائمیه'),
            array('state_id' => '17','name' => 'قادرآباد'),
            array('state_id' => '17','name' => 'قطب آباد'),
            array('state_id' => '17','name' => 'قطرویه'),
            array('state_id' => '17','name' => 'قیر'),
            array('state_id' => '17','name' => 'کارزین (فتح آباد)'),
            array('state_id' => '17','name' => 'کازرون'),
            array('state_id' => '17','name' => 'کامفیروز'),
            array('state_id' => '17','name' => 'کره ای'),
            array('state_id' => '17','name' => 'کنارتخته'),
            array('state_id' => '17','name' => 'کوار'),
            array('state_id' => '17','name' => 'گراش'),
            array('state_id' => '17','name' => 'گله دار'),
            array('state_id' => '17','name' => 'لار'),
            array('state_id' => '17','name' => 'لامرد'),
            array('state_id' => '17','name' => 'لپویی'),
            array('state_id' => '17','name' => 'لطیفی'),
            array('state_id' => '17','name' => 'مبارک آباددیز'),
            array('state_id' => '17','name' => 'مرودشت'),
            array('state_id' => '17','name' => 'مشکان'),
            array('state_id' => '17','name' => 'مصیری'),
            array('state_id' => '17','name' => 'مهر'),
            array('state_id' => '17','name' => 'میمند'),
            array('state_id' => '17','name' => 'نوبندگان'),
            array('state_id' => '17','name' => 'نوجین'),
            array('state_id' => '17','name' => 'نودان'),
            array('state_id' => '17','name' => 'نورآباد'),
            array('state_id' => '17','name' => 'نی ریز'),
            array('state_id' => '17','name' => 'وراوی'),
            array('state_id' => '18','name' => 'ارداق'),
            array('state_id' => '18','name' => 'اسفرورین'),
            array('state_id' => '18','name' => 'اقبالیه'),
            array('state_id' => '18','name' => 'الوند'),
            array('state_id' => '18','name' => 'آبگرم'),
            array('state_id' => '18','name' => 'آبیک'),
            array('state_id' => '18','name' => 'آوج'),
            array('state_id' => '18','name' => 'بوئین زهرا'),
            array('state_id' => '18','name' => 'بیدستان'),
            array('state_id' => '18','name' => 'تاکستان'),
            array('state_id' => '18','name' => 'خاکعلی'),
            array('state_id' => '18','name' => 'خرمدشت'),
            array('state_id' => '18','name' => 'دانسفهان'),
            array('state_id' => '18','name' => 'رازمیان'),
            array('state_id' => '18','name' => 'سگزآباد'),
            array('state_id' => '18','name' => 'سیردان'),
            array('state_id' => '18','name' => 'شال'),
            array('state_id' => '18','name' => 'شریفیه'),
            array('state_id' => '18','name' => 'ضیاآباد'),
            array('state_id' => '18','name' => 'قزوین'),
            array('state_id' => '18','name' => 'کوهین'),
            array('state_id' => '18','name' => 'محمدیه'),
            array('state_id' => '18','name' => 'محمودآباد نمونه'),
            array('state_id' => '18','name' => 'معلم کلایه'),
            array('state_id' => '18','name' => 'نرجه'),
            array('state_id' => '19','name' => 'جعفریه'),
            array('state_id' => '19','name' => 'دستجرد'),
            array('state_id' => '19','name' => 'سلفچگان'),
            array('state_id' => '19','name' => 'قم'),
            array('state_id' => '19','name' => 'قنوات'),
            array('state_id' => '19','name' => 'کهک'),
            array('state_id' => '20','name' => 'آرمرده'),
            array('state_id' => '20','name' => 'بابارشانی'),
            array('state_id' => '20','name' => 'بانه'),
            array('state_id' => '20','name' => 'بلبان آباد'),
            array('state_id' => '20','name' => 'بوئین سفلی'),
            array('state_id' => '20','name' => 'بیجار'),
            array('state_id' => '20','name' => 'چناره'),
            array('state_id' => '20','name' => 'دزج'),
            array('state_id' => '20','name' => 'دلبران'),
            array('state_id' => '20','name' => 'دهگلان'),
            array('state_id' => '20','name' => 'دیواندره'),
            array('state_id' => '20','name' => 'زرینه'),
            array('state_id' => '20','name' => 'سروآباد'),
            array('state_id' => '20','name' => 'سریش آباد'),
            array('state_id' => '20','name' => 'سقز'),
            array('state_id' => '20','name' => 'سنندج'),
            array('state_id' => '20','name' => 'شویشه'),
            array('state_id' => '20','name' => 'صاحب'),
            array('state_id' => '20','name' => 'قروه'),
            array('state_id' => '20','name' => 'کامیاران'),
            array('state_id' => '20','name' => 'کانی دینار'),
            array('state_id' => '20','name' => 'کانی سور'),
            array('state_id' => '20','name' => 'مریوان'),
            array('state_id' => '20','name' => 'موچش'),
            array('state_id' => '20','name' => 'یاسوکند'),
            array('state_id' => '21','name' => 'اختیارآباد'),
            array('state_id' => '21','name' => 'ارزوئیه'),
            array('state_id' => '21','name' => 'امین شهر'),
            array('state_id' => '21','name' => 'انار'),
            array('state_id' => '21','name' => 'اندوهجرد'),
            array('state_id' => '21','name' => 'باغین'),
            array('state_id' => '21','name' => 'بافت'),
            array('state_id' => '21','name' => 'بردسیر'),
            array('state_id' => '21','name' => 'بروات'),
            array('state_id' => '21','name' => 'بزنجان'),
            array('state_id' => '21','name' => 'بم'),
            array('state_id' => '21','name' => 'بهرمان'),
            array('state_id' => '21','name' => 'پاریز'),
            array('state_id' => '21','name' => 'جبالبارز'),
            array('state_id' => '21','name' => 'جوپار'),
            array('state_id' => '21','name' => 'جوزم'),
            array('state_id' => '21','name' => 'جیرفت'),
            array('state_id' => '21','name' => 'چترود'),
            array('state_id' => '21','name' => 'خاتون آباد'),
            array('state_id' => '21','name' => 'خانوک'),
            array('state_id' => '21','name' => 'خورسند'),
            array('state_id' => '21','name' => 'درب بهشت'),
            array('state_id' => '21','name' => 'دهج'),
            array('state_id' => '21','name' => 'رابر'),
            array('state_id' => '21','name' => 'راور'),
            array('state_id' => '21','name' => 'راین'),
            array('state_id' => '21','name' => 'رفسنجان'),
            array('state_id' => '21','name' => 'رودبار'),
            array('state_id' => '21','name' => 'ریحان شهر'),
            array('state_id' => '21','name' => 'زرند'),
            array('state_id' => '21','name' => 'زنگی آباد'),
            array('state_id' => '21','name' => 'زیدآباد'),
            array('state_id' => '21','name' => 'سیرجان'),
            array('state_id' => '21','name' => 'شهداد'),
            array('state_id' => '21','name' => 'شهربابک'),
            array('state_id' => '21','name' => 'صفائیه'),
            array('state_id' => '21','name' => 'عنبرآباد'),
            array('state_id' => '21','name' => 'فاریاب'),
            array('state_id' => '21','name' => 'فهرج'),
            array('state_id' => '21','name' => 'قلعه گنج'),
            array('state_id' => '21','name' => 'کاظم آباد'),
            array('state_id' => '21','name' => 'کرمان'),
            array('state_id' => '21','name' => 'کشکوئیه'),
            array('state_id' => '21','name' => 'کهنوج'),
            array('state_id' => '21','name' => 'کوهبنان'),
            array('state_id' => '21','name' => 'کیانشهر'),
            array('state_id' => '21','name' => 'گلباف'),
            array('state_id' => '21','name' => 'گلزار'),
            array('state_id' => '21','name' => 'لاله زار'),
            array('state_id' => '21','name' => 'ماهان'),
            array('state_id' => '21','name' => 'محمدآباد'),
            array('state_id' => '21','name' => 'محی آباد'),
            array('state_id' => '21','name' => 'مردهک'),
            array('state_id' => '21','name' => 'مس سرچشمه'),
            array('state_id' => '21','name' => 'منوجان'),
            array('state_id' => '21','name' => 'نجف شهر'),
            array('state_id' => '21','name' => 'نرماشیر'),
            array('state_id' => '21','name' => 'نظام شهر'),
            array('state_id' => '21','name' => 'نگار'),
            array('state_id' => '21','name' => 'نودژ'),
            array('state_id' => '21','name' => 'هجدک'),
            array('state_id' => '21','name' => 'یزدان شهر'),
            array('state_id' => '22','name' => 'ازگله'),
            array('state_id' => '22','name' => 'اسلام آباد غرب'),
            array('state_id' => '22','name' => 'باینگان'),
            array('state_id' => '22','name' => 'بیستون'),
            array('state_id' => '22','name' => 'پاوه'),
            array('state_id' => '22','name' => 'تازه آباد'),
            array('state_id' => '22','name' => 'جوان رود'),
            array('state_id' => '22','name' => 'حمیل'),
            array('state_id' => '22','name' => 'ماهیدشت'),
            array('state_id' => '22','name' => 'روانسر'),
            array('state_id' => '22','name' => 'سرپل ذهاب'),
            array('state_id' => '22','name' => 'سرمست'),
            array('state_id' => '22','name' => 'سطر'),
            array('state_id' => '22','name' => 'سنقر'),
            array('state_id' => '22','name' => 'سومار'),
            array('state_id' => '22','name' => 'شاهو'),
            array('state_id' => '22','name' => 'صحنه'),
            array('state_id' => '22','name' => 'قصرشیرین'),
            array('state_id' => '22','name' => 'کرمانشاه'),
            array('state_id' => '22','name' => 'کرندغرب'),
            array('state_id' => '22','name' => 'کنگاور'),
            array('state_id' => '22','name' => 'کوزران'),
            array('state_id' => '22','name' => 'گهواره'),
            array('state_id' => '22','name' => 'گیلانغرب'),
            array('state_id' => '22','name' => 'میان راهان'),
            array('state_id' => '22','name' => 'نودشه'),
            array('state_id' => '22','name' => 'نوسود'),
            array('state_id' => '22','name' => 'هرسین'),
            array('state_id' => '22','name' => 'هلشی'),
            array('state_id' => '23','name' => 'باشت'),
            array('state_id' => '23','name' => 'پاتاوه'),
            array('state_id' => '23','name' => 'چرام'),
            array('state_id' => '23','name' => 'چیتاب'),
            array('state_id' => '23','name' => 'دهدشت'),
            array('state_id' => '23','name' => 'دوگنبدان'),
            array('state_id' => '23','name' => 'دیشموک'),
            array('state_id' => '23','name' => 'سوق'),
            array('state_id' => '23','name' => 'سی سخت'),
            array('state_id' => '23','name' => 'قلعه رئیسی'),
            array('state_id' => '23','name' => 'گراب سفلی'),
            array('state_id' => '23','name' => 'لنده'),
            array('state_id' => '23','name' => 'لیکک'),
            array('state_id' => '23','name' => 'مادوان'),
            array('state_id' => '23','name' => 'مارگون'),
            array('state_id' => '23','name' => 'یاسوج'),
            array('state_id' => '24','name' => 'انبارآلوم'),
            array('state_id' => '24','name' => 'اینچه برون'),
            array('state_id' => '24','name' => 'آزادشهر'),
            array('state_id' => '24','name' => 'آق قلا'),
            array('state_id' => '24','name' => 'بندرترکمن'),
            array('state_id' => '24','name' => 'بندرگز'),
            array('state_id' => '24','name' => 'جلین'),
            array('state_id' => '24','name' => 'خان ببین'),
            array('state_id' => '24','name' => 'دلند'),
            array('state_id' => '24','name' => 'رامیان'),
            array('state_id' => '24','name' => 'سرخنکلاته'),
            array('state_id' => '24','name' => 'سیمین شهر'),
            array('state_id' => '24','name' => 'علی آباد کتول'),
            array('state_id' => '24','name' => 'فاضل آباد'),
            array('state_id' => '24','name' => 'کردکوی'),
            array('state_id' => '24','name' => 'کلاله'),
            array('state_id' => '24','name' => 'گالیکش'),
            array('state_id' => '24','name' => 'گرگان'),
            array('state_id' => '24','name' => 'گمیش تپه'),
            array('state_id' => '24','name' => 'گنبدکاووس'),
            array('state_id' => '24','name' => 'مراوه'),
            array('state_id' => '24','name' => 'مینودشت'),
            array('state_id' => '24','name' => 'نگین شهر'),
            array('state_id' => '24','name' => 'نوده خاندوز'),
            array('state_id' => '24','name' => 'نوکنده'),
            array('state_id' => '25','name' => 'ازنا'),
            array('state_id' => '25','name' => 'اشترینان'),
            array('state_id' => '25','name' => 'الشتر'),
            array('state_id' => '25','name' => 'الیگودرز'),
            array('state_id' => '25','name' => 'بروجرد'),
            array('state_id' => '25','name' => 'پلدختر'),
            array('state_id' => '25','name' => 'چالانچولان'),
            array('state_id' => '25','name' => 'چغلوندی'),
            array('state_id' => '25','name' => 'چقابل'),
            array('state_id' => '25','name' => 'خرم آباد'),
            array('state_id' => '25','name' => 'درب گنبد'),
            array('state_id' => '25','name' => 'دورود'),
            array('state_id' => '25','name' => 'زاغه'),
            array('state_id' => '25','name' => 'سپیددشت'),
            array('state_id' => '25','name' => 'سراب دوره'),
            array('state_id' => '25','name' => 'فیروزآباد'),
            array('state_id' => '25','name' => 'کونانی'),
            array('state_id' => '25','name' => 'کوهدشت'),
            array('state_id' => '25','name' => 'گراب'),
            array('state_id' => '25','name' => 'معمولان'),
            array('state_id' => '25','name' => 'مومن آباد'),
            array('state_id' => '25','name' => 'نورآباد'),
            array('state_id' => '25','name' => 'ویسیان'),
            array('state_id' => '26','name' => 'احمدسرگوراب'),
            array('state_id' => '26','name' => 'اسالم'),
            array('state_id' => '26','name' => 'اطاقور'),
            array('state_id' => '26','name' => 'املش'),
            array('state_id' => '26','name' => 'آستارا'),
            array('state_id' => '26','name' => 'آستانه اشرفیه'),
            array('state_id' => '26','name' => 'بازار جمعه'),
            array('state_id' => '26','name' => 'بره سر'),
            array('state_id' => '26','name' => 'بندرانزلی'),
            array('state_id' => '26','name' => 'پره سر'),
            array('state_id' => '26','name' => 'تالش'),
            array('state_id' => '26','name' => 'توتکابن'),
            array('state_id' => '26','name' => 'جیرنده'),
            array('state_id' => '26','name' => 'چابکسر'),
            array('state_id' => '26','name' => 'چاف و چمخاله'),
            array('state_id' => '26','name' => 'چوبر'),
            array('state_id' => '26','name' => 'حویق'),
            array('state_id' => '26','name' => 'خشکبیجار'),
            array('state_id' => '26','name' => 'خمام'),
            array('state_id' => '26','name' => 'دیلمان'),
            array('state_id' => '26','name' => 'رانکوه'),
            array('state_id' => '26','name' => 'رحیم آباد'),
            array('state_id' => '26','name' => 'رستم آباد'),
            array('state_id' => '26','name' => 'رشت'),
            array('state_id' => '26','name' => 'رضوانشهر'),
            array('state_id' => '26','name' => 'رودبار'),
            array('state_id' => '26','name' => 'رودبنه'),
            array('state_id' => '26','name' => 'رودسر'),
            array('state_id' => '26','name' => 'سنگر'),
            array('state_id' => '26','name' => 'سیاهکل'),
            array('state_id' => '26','name' => 'شفت'),
            array('state_id' => '26','name' => 'شلمان'),
            array('state_id' => '26','name' => 'صومعه سرا'),
            array('state_id' => '26','name' => 'فومن'),
            array('state_id' => '26','name' => 'کلاچای'),
            array('state_id' => '26','name' => 'کوچصفهان'),
            array('state_id' => '26','name' => 'کومله'),
            array('state_id' => '26','name' => 'کیاشهر'),
            array('state_id' => '26','name' => 'گوراب زرمیخ'),
            array('state_id' => '26','name' => 'لاهیجان'),
            array('state_id' => '26','name' => 'لشت نشا'),
            array('state_id' => '26','name' => 'لنگرود'),
            array('state_id' => '26','name' => 'لوشان'),
            array('state_id' => '26','name' => 'لولمان'),
            array('state_id' => '26','name' => 'لوندویل'),
            array('state_id' => '26','name' => 'لیسار'),
            array('state_id' => '26','name' => 'ماسال'),
            array('state_id' => '26','name' => 'ماسوله'),
            array('state_id' => '26','name' => 'مرجقل'),
            array('state_id' => '26','name' => 'منجیل'),
            array('state_id' => '26','name' => 'واجارگاه'),
            array('state_id' => '27','name' => 'امیرکلا'),
            array('state_id' => '27','name' => 'ایزدشهر'),
            array('state_id' => '27','name' => 'آلاشت'),
            array('state_id' => '27','name' => 'آمل'),
            array('state_id' => '27','name' => 'بابل'),
            array('state_id' => '27','name' => 'بابلسر'),
            array('state_id' => '27','name' => 'بالاده'),
            array('state_id' => '27','name' => 'بهشهر'),
            array('state_id' => '27','name' => 'بهنمیر'),
            array('state_id' => '27','name' => 'پل سفید'),
            array('state_id' => '27','name' => 'تنکابن'),
            array('state_id' => '27','name' => 'جویبار'),
            array('state_id' => '27','name' => 'چالوس'),
            array('state_id' => '27','name' => 'چمستان'),
            array('state_id' => '27','name' => 'خرم آباد'),
            array('state_id' => '27','name' => 'خلیل شهر'),
            array('state_id' => '27','name' => 'خوش رودپی'),
            array('state_id' => '27','name' => 'دابودشت'),
            array('state_id' => '27','name' => 'رامسر'),
            array('state_id' => '27','name' => 'رستمکلا'),
            array('state_id' => '27','name' => 'رویان'),
            array('state_id' => '27','name' => 'رینه'),
            array('state_id' => '27','name' => 'زرگرمحله'),
            array('state_id' => '27','name' => 'زیرآب'),
            array('state_id' => '27','name' => 'ساری'),
            array('state_id' => '27','name' => 'سرخرود'),
            array('state_id' => '27','name' => 'سلمان شهر'),
            array('state_id' => '27','name' => 'سورک'),
            array('state_id' => '27','name' => 'شیرگاه'),
            array('state_id' => '27','name' => 'شیرود'),
            array('state_id' => '27','name' => 'عباس آباد'),
            array('state_id' => '27','name' => 'فریدونکنار'),
            array('state_id' => '27','name' => 'فریم'),
            array('state_id' => '27','name' => 'قائم شهر'),
            array('state_id' => '27','name' => 'کتالم'),
            array('state_id' => '27','name' => 'کلارآباد'),
            array('state_id' => '27','name' => 'کلاردشت'),
            array('state_id' => '27','name' => 'کله بست'),
            array('state_id' => '27','name' => 'کوهی خیل'),
            array('state_id' => '27','name' => 'کیاسر'),
            array('state_id' => '27','name' => 'کیاکلا'),
            array('state_id' => '27','name' => 'گتاب'),
            array('state_id' => '27','name' => 'گزنک'),
            array('state_id' => '27','name' => 'گلوگاه'),
            array('state_id' => '27','name' => 'محمودآباد'),
            array('state_id' => '27','name' => 'مرزن آباد'),
            array('state_id' => '27','name' => 'مرزیکلا'),
            array('state_id' => '27','name' => 'نشتارود'),
            array('state_id' => '27','name' => 'نکا'),
            array('state_id' => '27','name' => 'نور'),
            array('state_id' => '27','name' => 'نوشهر'),
            array('state_id' => '28','name' => 'اراک'),
            array('state_id' => '28','name' => 'آستانه'),
            array('state_id' => '28','name' => 'آشتیان'),
            array('state_id' => '28','name' => 'پرندک'),
            array('state_id' => '28','name' => 'تفرش'),
            array('state_id' => '28','name' => 'توره'),
            array('state_id' => '28','name' => 'جاورسیان'),
            array('state_id' => '28','name' => 'خشکرود'),
            array('state_id' => '28','name' => 'خمین'),
            array('state_id' => '28','name' => 'خنداب'),
            array('state_id' => '28','name' => 'داودآباد'),
            array('state_id' => '28','name' => 'دلیجان'),
            array('state_id' => '28','name' => 'رازقان'),
            array('state_id' => '28','name' => 'زاویه'),
            array('state_id' => '28','name' => 'ساروق'),
            array('state_id' => '28','name' => 'ساوه'),
            array('state_id' => '28','name' => 'سنجان'),
            array('state_id' => '28','name' => 'شازند'),
            array('state_id' => '28','name' => 'غرق آباد'),
            array('state_id' => '28','name' => 'فرمهین'),
            array('state_id' => '28','name' => 'قورچی باشی'),
            array('state_id' => '28','name' => 'کرهرود'),
            array('state_id' => '28','name' => 'کمیجان'),
            array('state_id' => '28','name' => 'مامونیه'),
            array('state_id' => '28','name' => 'محلات'),
            array('state_id' => '28','name' => 'مهاجران'),
            array('state_id' => '28','name' => 'میلاجرد'),
            array('state_id' => '28','name' => 'نراق'),
            array('state_id' => '28','name' => 'نوبران'),
            array('state_id' => '28','name' => 'نیمور'),
            array('state_id' => '28','name' => 'هندودر'),
            array('state_id' => '29','name' => 'ابوموسی'),
            array('state_id' => '29','name' => 'بستک'),
            array('state_id' => '29','name' => 'بندرجاسک'),
            array('state_id' => '29','name' => 'بندرچارک'),
            array('state_id' => '29','name' => 'بندرخمیر'),
            array('state_id' => '29','name' => 'بندرعباس'),
            array('state_id' => '29','name' => 'بندرلنگه'),
            array('state_id' => '29','name' => 'بیکا'),
            array('state_id' => '29','name' => 'پارسیان'),
            array('state_id' => '29','name' => 'تخت'),
            array('state_id' => '29','name' => 'جناح'),
            array('state_id' => '29','name' => 'حاجی آباد'),
            array('state_id' => '29','name' => 'درگهان'),
            array('state_id' => '29','name' => 'دهبارز'),
            array('state_id' => '29','name' => 'رویدر'),
            array('state_id' => '29','name' => 'زیارتعلی'),
            array('state_id' => '29','name' => 'سردشت'),
            array('state_id' => '29','name' => 'سندرک'),
            array('state_id' => '29','name' => 'سوزا'),
            array('state_id' => '29','name' => 'سیریک'),
            array('state_id' => '29','name' => 'فارغان'),
            array('state_id' => '29','name' => 'فین'),
            array('state_id' => '29','name' => 'قشم'),
            array('state_id' => '29','name' => 'قلعه قاضی'),
            array('state_id' => '29','name' => 'کنگ'),
            array('state_id' => '29','name' => 'کوشکنار'),
            array('state_id' => '29','name' => 'کیش'),
            array('state_id' => '29','name' => 'گوهران'),
            array('state_id' => '29','name' => 'میناب'),
            array('state_id' => '29','name' => 'هرمز'),
            array('state_id' => '29','name' => 'هشتبندی'),
            array('state_id' => '30','name' => 'ازندریان'),
            array('state_id' => '30','name' => 'اسدآباد'),
            array('state_id' => '30','name' => 'برزول'),
            array('state_id' => '30','name' => 'بهار'),
            array('state_id' => '30','name' => 'تویسرکان'),
            array('state_id' => '30','name' => 'جورقان'),
            array('state_id' => '30','name' => 'جوکار'),
            array('state_id' => '30','name' => 'دمق'),
            array('state_id' => '30','name' => 'رزن'),
            array('state_id' => '30','name' => 'زنگنه'),
            array('state_id' => '30','name' => 'سامن'),
            array('state_id' => '30','name' => 'سرکان'),
            array('state_id' => '30','name' => 'شیرین سو'),
            array('state_id' => '30','name' => 'صالح آباد'),
            array('state_id' => '30','name' => 'فامنین'),
            array('state_id' => '30','name' => 'فرسفج'),
            array('state_id' => '30','name' => 'فیروزان'),
            array('state_id' => '30','name' => 'قروه درجزین'),
            array('state_id' => '30','name' => 'قهاوند'),
            array('state_id' => '30','name' => 'کبودر آهنگ'),
            array('state_id' => '30','name' => 'گل تپه'),
            array('state_id' => '30','name' => 'گیان'),
            array('state_id' => '30','name' => 'لالجین'),
            array('state_id' => '30','name' => 'مریانج'),
            array('state_id' => '30','name' => 'ملایر'),
            array('state_id' => '30','name' => 'نهاوند'),
            array('state_id' => '30','name' => 'همدان'),
            array('state_id' => '31','name' => 'ابرکوه'),
            array('state_id' => '31','name' => 'احمدآباد'),
            array('state_id' => '31','name' => 'اردکان'),
            array('state_id' => '31','name' => 'اشکذر'),
            array('state_id' => '31','name' => 'بافق'),
            array('state_id' => '31','name' => 'بفروئیه'),
            array('state_id' => '31','name' => 'بهاباد'),
            array('state_id' => '31','name' => 'تفت'),
            array('state_id' => '31','name' => 'حمیدیا'),
            array('state_id' => '31','name' => 'خضرآباد'),
            array('state_id' => '31','name' => 'دیهوک'),
            array('state_id' => '31','name' => 'زارچ'),
            array('state_id' => '31','name' => 'شاهدیه'),
            array('state_id' => '31','name' => 'طبس'),
            array('state_id' => '31','name' => 'عقدا'),
            array('state_id' => '31','name' => 'مروست'),
            array('state_id' => '31','name' => 'مهردشت'),
            array('state_id' => '31','name' => 'مهریز'),
            array('state_id' => '31','name' => 'میبد'),
            array('state_id' => '31','name' => 'ندوشن'),
            array('state_id' => '31','name' => 'نیر'),
            array('state_id' => '31','name' => 'هرات'),
            array('state_id' => '31','name' => 'یزد'),
            array('state_id' => '8','name' => 'پرند'),
            array('state_id' => '5','name' => 'فردیس'),
            array('state_id' => '5','name' => 'مارلیک'),
            array('state_id' => '27','name' => 'سادات شهر')
        );
        DB::table("cities")->insert($cities);
    }
}
